import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full min-h-screen flex flex-row">
          <aside className="border-r min-w-[250px] p-5 flex flex-col gap-x-2">
            <Link href="/static">Static</Link>
            <Link href="/dynamic">Dynamic</Link>
            <Link href="/isr">ISR</Link>
          </aside>
          <main className="p-5">{children}</main>
        </div>
      </body>
    </html>
  );
}
